### ISSUE TITLE
Multiple runs

### ISSUE THREAD

**Issue by kaihendry** [tcnksm/go-httpstat#2]
When I loop over your example code:

http://s.natalian.org/2016-10-05/main.go

I get odd results after the first:

http://s.natalian.org/2016-10-05/output.txt

What am I missing? I guess result needs to be re-initialised?

**Comment by tcnksm** [comment]
Thank you for report. 

Umm, it's something wrong. I will look into that.

**Comment by tcnksm** [comment]
Found it's because of keep-alive. Fixed it https://github.com/tcnksm/go-httpstat/pull/3
